### ISSUE TITLE
Issue regarding _Paytoken param in listNFT

### ISSUE THREAD

**Issue by testingaccount-eth** [kofkuiper/kuiper-nft-marketplace#1]
Hey kuiper, just need you help regarding what should be the address in _paytoken , I created a token and added its address but it is showing the same error "invalid pay token". Please help

**Comment by kofkuiper** [comment]
Hey @testingaccount-eth, I'm not sure your token address is already added to the payable token on the marketplace? If not added, it will revert to 'invalid pay token' when you call `listNFT` function. So after creating a token, you (as marketplace owner) need to add a payable token by calling the  [addPayableToken ](https://github.com/kofkuiper/kuiper-nft-marketplace/blob/391f5d97d054782bc8c5bfa0cddf0c10c355250c/contracts/KuiperMarketplace.sol#L635) function. I appreciate you flagging issue, hope this fixes the issue!
